# Generated by Django 2.1.7 on 2019-02-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bootcamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.Bootcamp')),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ideas.Student'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice1', to='ideas.Idea'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice2', to='ideas.Idea'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice3', to='ideas.Idea'),
        ),
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Student'),
        ),
    ]
